/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.util.Random;

/**
 *
 * @author Admin
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        setResizable(false);
        initComponents();

    }
    Random rnd = new Random();
    int dado = rnd.nextInt(3);
    int azul = 1, naranja = 0, posicionAzul = 0, posicionNaranja = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 690, -1, -1));

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 110, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marte_solo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venus_solo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tierra_p1_p2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jupiter_vacio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 160, 200));

        jButton1.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton volver.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 690, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Space.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1281, 777));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Landing landing = new Landing();
        landing.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (azul > naranja) {
            switch (dado) {
                case 0:
                    naranja++;
                    break;
                case 1:
                    posicionAzul++;
                    naranja++;
                    break;
                case 2:
                    naranja++;
                    posicionAzul += 2;
                    break;

            }
        } else {
            switch (dado) {
                case 0:
                    azul++;
                    break;
                case 1:
                    posicionNaranja++;
                    azul++;
                    break;
                case 2:
                    azul++;
                    posicionNaranja += 2;
                    break;
            }
        }

        if (posicionAzul == posicionNaranja) {
            switch (posicionAzul) {
                case 1:
                    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
                case 2:
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
                case 3:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
            }
        } else if (posicionAzul > posicionNaranja) {
            switch (posicionAzul) {
                case 1:
                    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
                case 2:
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
                case 3:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
            }
        } else {
            switch (posicionAzul) {
                case 1:
                    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
                case 2:
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
                case 3:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (azul > naranja) {
            switch (dado) {
                case 0:
                    naranja++;
                    break;
                case 1:
                    posicionAzul++;
                    naranja++;
                    break;
                case 2:
                    naranja++;
                    posicionAzul += 2;
                    break;

            }
        } else {
            switch (dado) {
                case 0:
                    azul++;
                    break;
                case 1:
                    posicionNaranja++;
                    azul++;
                    break;
                case 2:
                    azul++;
                    posicionNaranja += 2;
                    break;
            }
        }

        if (posicionAzul == posicionNaranja) {
            switch (posicionAzul) {
                case 1:
                    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
                case 2:
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
                case 3:
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton jugar apretado.png")));
                    break;
            }
        } else if (posicionAzul > posicionNaranja) {
            switch (posicionAzul) {
                case 1:

                    break;
                case 2:

                    break;
                case 3:

                    break;
            }
        } else {
            switch (posicionAzul) {
                case 1:

                    break;
                case 2:

                    break;
                case 3:

                    break;
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
